-- Brick Breaker
-- Platform: LÖVE2D
-- Single file, no external assets

-- =============================================================================
-- GLOBAL STATE
-- =============================================================================

G = {}

G.state = 'menu' -- menu/playing/dead/level_complete/game_over
G.score = 0
G.lives = 0
G.level = 0
G.timer = 0.0

G.ball = {
    x = 0,
    y = 0,
    vx = 0,
    vy = 0,
    r = 8
}

G.paddle = {
    x = 0,
    y = 0,
    w = 0,
    h = 12
}

G.bricks = {}

G.BASE_SPEED = 300
G.BALL_SPEED = 0

G.fontLarge  = nil
G.fontMedium = nil
G.fontSmall  = nil

-- =============================================================================
-- INITIALIZATION (TICKET-1 — generated by gemini-flash, reviewed by claude-sonnet)
-- =============================================================================

function resetBall()
    G.ball.x = 400
    G.ball.y = 520
    local angle = -math.pi / 4
    G.ball.vx = G.BALL_SPEED * math.cos(angle)
    G.ball.vy = G.BALL_SPEED * math.sin(angle)
end

function initBricks()
    G.bricks = {}
    local brickWidth  = 58
    local brickHeight = 20
    local gap         = 4
    local startX      = 20
    local startY      = 60
    local numCols     = 12
    local numRows     = 8

    local colors = {
        { r = 1,   g = 0.2, b = 0.2, points = 70 }, -- Red    (rows 1-2)
        { r = 1,   g = 0.6, b = 0.1, points = 50 }, -- Orange (rows 3-4)
        { r = 1,   g = 1,   b = 0.1, points = 30 }, -- Yellow (rows 5-6)
        { r = 0.2, g = 0.9, b = 0.2, points = 10 }, -- Green  (rows 7-8)
    }

    for row = 1, numRows do
        local cd
        if     row <= 2 then cd = colors[1]
        elseif row <= 4 then cd = colors[2]
        elseif row <= 6 then cd = colors[3]
        else                 cd = colors[4]
        end

        for col = 1, numCols do
            local bx = startX + (col - 1) * (brickWidth + gap)
            local by = startY + (row - 1) * (brickHeight + gap)
            table.insert(G.bricks, {
                x      = bx,
                y      = by,
                w      = brickWidth,
                h      = brickHeight,
                alive  = true,
                color  = { cd.r, cd.g, cd.b },
                points = cd.points,
            })
        end
    end
end

function resetLevel()
    G.BALL_SPEED = G.BASE_SPEED * (1.1 ^ (G.level - 1))
    G.paddle.w   = math.max(60, 100 - (G.level - 1) * 10)
    G.paddle.x   = 400 - G.paddle.w / 2
    initBricks()
    resetBall()
    G.timer = 0
end

function resetGame()
    G.score      = 0
    G.lives      = 3
    G.level      = 1
    G.BASE_SPEED = 300
    G.paddle     = { x = 350, y = 540, w = 100, h = 12 }
    G.ball       = { x = 400, y = 520, vx = 0, vy = 0, r = 8 }
    G.bricks     = {}
    resetLevel()
end

function love.load()
    love.window.setMode(800, 600)
    love.window.setTitle('Brick Breaker')
    resetGame()
    G.state = 'menu'

    G.fontLarge  = love.graphics.newFont(48)
    G.fontMedium = love.graphics.newFont(28)
    G.fontSmall  = love.graphics.newFont(18)
end

function love.keypressed(key)
    if key == 'escape' then
        love.event.quit()
        return
    end

    if G.state == 'menu' then
        G.state = 'playing'
    elseif G.state == 'game_over' then
        resetGame()
        G.state = 'menu'
    end
end

function love.mousemoved(x, y, dx, dy)
    if G.state == 'playing' or G.state == 'dead' then
        G.paddle.x = math.max(20, math.min(760 - G.paddle.w, x - G.paddle.w / 2))
    end
end

-- =============================================================================
-- GAME LOGIC (TICKET-2 — generated by gemini-flash, reviewed + patched by claude-sonnet)
-- Patch: removed erroneous resetGame() call on game_over transition (would zero
--        the score before the game_over screen could display it)
-- =============================================================================

function love.update(dt)
    if G.state == 'dead' then
        G.timer = G.timer - dt
        if G.timer <= 0 then
            resetBall()
            G.state = 'playing'
        end

    elseif G.state == 'level_complete' then
        G.timer = G.timer - dt
        if G.timer <= 0 then
            G.level = G.level + 1
            resetLevel()
            G.state = 'playing'
        end

    elseif G.state == 'playing' then
        -- 1. Move ball
        G.ball.x = G.ball.x + G.ball.vx * dt
        G.ball.y = G.ball.y + G.ball.vy * dt

        local r = G.ball.r

        -- 2. Wall collisions
        if G.ball.x - r < 20 then
            G.ball.x  = 20 + r
            G.ball.vx = math.abs(G.ball.vx)
        end
        if G.ball.x + r > 780 then
            G.ball.x  = 780 - r
            G.ball.vx = -math.abs(G.ball.vx)
        end
        if G.ball.y - r < 0 then
            G.ball.y  = r
            G.ball.vy = math.abs(G.ball.vy)
        end

        -- 3. Paddle collision (AABB + downward check)
        local bx1 = G.ball.x - r
        local by1 = G.ball.y - r
        local bx2 = G.ball.x + r
        local by2 = G.ball.y + r

        local px1 = G.paddle.x
        local py1 = G.paddle.y
        local px2 = px1 + G.paddle.w
        local py2 = py1 + G.paddle.h

        if bx2 > px1 and bx1 < px2 and by2 > py1 and by1 < py2 and G.ball.vy > 0 then
            local hitPos   = (G.ball.x - G.paddle.x) / G.paddle.w
            local angle_deg
            if     hitPos < 0.2 then angle_deg = -60
            elseif hitPos < 0.4 then angle_deg = -30
            elseif hitPos < 0.6 then angle_deg =   0
            elseif hitPos < 0.8 then angle_deg =  30
            else                      angle_deg =  60
            end

            local angle_rad = angle_deg * math.pi / 180
            G.ball.vx = G.BALL_SPEED * math.sin(angle_rad)
            G.ball.vy = -G.BALL_SPEED * math.cos(angle_rad)
            G.ball.y  = G.paddle.y - r
        end

        -- 4. Brick collision (AABB, one brick per frame)
        for i, brick in ipairs(G.bricks) do
            if brick.alive then
                local br_x1 = brick.x
                local br_y1 = brick.y
                local br_x2 = brick.x + brick.w
                local br_y2 = brick.y + brick.h

                if bx2 > br_x1 and bx1 < br_x2 and by2 > br_y1 and by1 < br_y2 then
                    brick.alive   = false
                    G.score       = G.score + brick.points

                    local bcx = brick.x + brick.w / 2
                    local bcy = brick.y + brick.h / 2
                    local overlapX = (r + brick.w / 2) - math.abs(G.ball.x - bcx)
                    local overlapY = (r + brick.h / 2) - math.abs(G.ball.y - bcy)

                    if overlapX < overlapY then
                        G.ball.vx = -G.ball.vx
                        if G.ball.x < bcx then
                            G.ball.x = brick.x - r
                        else
                            G.ball.x = brick.x + brick.w + r
                        end
                    else
                        G.ball.vy = -G.ball.vy
                        if G.ball.y < bcy then
                            G.ball.y = brick.y - r
                        else
                            G.ball.y = brick.y + brick.h + r
                        end
                    end
                    break
                end
            end
        end

        -- 5. Ball lost
        if G.ball.y - r > 600 then
            G.lives = G.lives - 1
            if G.lives <= 0 then
                G.state = 'game_over'   -- score preserved for display; resetGame() on keypress
            else
                G.timer = 1.5
                G.state = 'dead'
            end
        end

        -- 6. Level complete
        local alive = 0
        for _, brick in ipairs(G.bricks) do
            if brick.alive then alive = alive + 1 end
        end
        if alive == 0 then
            G.timer = 2.0
            G.state = 'level_complete'
        end
    end
end

-- =============================================================================
-- RENDERING (TICKET-3 — generated by gemini-flash, reviewed by claude-sonnet)
-- =============================================================================

local function drawGame()
    for _, brick in ipairs(G.bricks) do
        if brick.alive then
            love.graphics.setColor(brick.color[1], brick.color[2], brick.color[3])
            love.graphics.rectangle('fill', brick.x, brick.y, brick.w, brick.h)
        end
    end

    love.graphics.setColor(1, 1, 1)
    love.graphics.rectangle('fill', G.paddle.x, G.paddle.y, G.paddle.w, G.paddle.h)

    love.graphics.setColor(1, 1, 1)
    love.graphics.circle('fill', G.ball.x, G.ball.y, G.ball.r)
end

local function drawHUD()
    love.graphics.setColor(1, 1, 1)
    love.graphics.setFont(G.fontSmall)
    love.graphics.print('SCORE: ' .. G.score, 25, 10)
    love.graphics.printf('LEVEL: ' .. G.level, 0, 10, 800, 'center')
    love.graphics.printf('LIVES: ' .. G.lives, 0, 10, 780, 'right')
end

function love.draw()
    love.graphics.clear(0, 0, 0)

    if G.state == 'menu' then
        love.graphics.setColor(1, 1, 1)
        love.graphics.setFont(G.fontLarge)
        love.graphics.printf('BRICK BREAKER', 0, 240, 800, 'center')
        love.graphics.setFont(G.fontSmall)
        love.graphics.printf('Press any key to start', 0, 310, 800, 'center')

    elseif G.state == 'playing' or G.state == 'dead' then
        drawGame()
        drawHUD()

    elseif G.state == 'level_complete' then
        drawGame()
        drawHUD()
        love.graphics.setColor(1, 1, 1)
        love.graphics.setFont(G.fontLarge)
        love.graphics.printf('LEVEL COMPLETE!', 0, 240, 800, 'center')
        love.graphics.setFont(G.fontSmall)
        love.graphics.printf('Get ready...', 0, 310, 800, 'center')

    elseif G.state == 'game_over' then
        love.graphics.setColor(1, 1, 1)
        love.graphics.setFont(G.fontLarge)
        love.graphics.printf('GAME OVER', 0, 200, 800, 'center')
        love.graphics.setFont(G.fontMedium)
        love.graphics.printf('SCORE: ' .. G.score, 0, 280, 800, 'center')
        love.graphics.setFont(G.fontSmall)
        love.graphics.printf('Press any key to continue', 0, 340, 800, 'center')
    end
end
